'''
    This file stores all discipline specific prompt of MOOSE-Chem2. 

    For MOOSE-Chem2 to be adapted to another discipline, just create another file with the same variables in the file, but replace the chemistry specific prompt to the new discipline specific prompt.
    
    The main difference is the description of the hierarchies in the new discipline, and the new examples in the new discipline in terms of the expected output hypothesis from each of the hierarchy (e.g., hyp_example_hierarchy_1/2/3/4/5).
'''

print("INFO: discipline_specific_prompt_geophysics.py is loaded.")

# hypothesis examples to show to the framework, as the goals
hyp_example_hierarchy_1 = "Seismic activity along the Main Himalayan Thrust (MHT) displays a characteristic bimodal behavior, consisting of two distinct types of earthquakes: frequent, moderate-magnitude blind ruptures (Mw ≤ 7.8) confined to the downdip portion of the fault, and rare, great-magnitude earthquakes (Mw > 8) that rupture the entire seismogenic width and reach the Himalayan front. This pattern is a fundamental property of the tectonic regime in the Nepal Himalaya, not merely an artifact of limited historical data. Understanding and reproducing this bimodality is critical for accurate long-term seismic hazard assessment."
hyp_example_hierarchy_2 = "The observed bimodal seismicity in the central Himalaya arises from the interaction of fault geometry and fault friction, governed by physical laws of stress accumulation, strain release, and deformation under tectonic loading. Specifically, the ramp-flat-ramp geometry of the MHT introduces along-dip strength excess gradients, while rate-dependent frictional behavior enables rupture segmentation and transition between pulse-like and crack-like slip modes. This physical interplay governs where ruptures initiate, how far they propagate, and why they sometimes remain blind or become surface-breaking. The combination of elasto-visco-plastic rheology and fault segmentation leads naturally to an alternation between moderate and great earthquakes over multiple seismic cycles."
hyp_example_hierarchy_3 = "The governing physical processes responsible for bimodal seismicity along the MHT — including the effects of non-planar geometry, strength excess, and rate-dependent fault friction — can be accurately captured using a two-dimensional visco-elasto-plastic numerical model. Implemented on a staggered Eulerian grid with Lagrangian markers and constrained by real Himalayan geophysical data, the model solves conservation equations of mass, momentum, and energy. It accounts for thermal gradients, plastic yielding, aseismic creep, and spontaneous rupture propagation. This computational framework demonstrates that, even in the absence of ad hoc rupture boundaries or external forcing, partial and complete earthquakes emerge naturally, replicating the empirical bimodal pattern. Therefore, this modeling strategy provides a valid and predictive tool for studying the physical drivers of complex seismic behaviors in the Himalaya."
hyp_example_hierarchy_4 = "The emergence of bimodal seismicity in the central Himalaya, characterized by alternating moderate (Mw ≤ 7.8) and great (Mw > 8) earthquakes, is not only governed by the physical principles of frictional weakening and fault geometry (Hierarchy 2), nor merely replicable through generic visco-elasto-plastic numerical frameworks (Hierarchy 3), but is critically dependent on specific, physically grounded parameterizations of the Main Himalayan Thrust (MHT). These include: a ramp-flat-ramp fault geometry inferred from seismic and geodetic surveys; a fault friction coefficient (μs) in the range 0.06–0.2 consistent with geological and thermomechanical constraints; a rate-dependent friction weakening law modulated by slip velocity (with γ = 1 − μd/μs); and a thermally defined transition from brittle to ductile behavior around 400–450 °C at 18–20 km depth. The combined spatial distribution of stress, strength, and slip evolves through these parameters to produce earthquake cycles where partial ruptures load up the shallow fault segments until a critical strength threshold is overcome, resulting in infrequent but large full-rupture events."
hyp_example_hierarchy_5 = "To accurately simulate the bimodal seismic behavior of the Main Himalayan Thrust (MHT), which arises from complex interactions of fault friction, geometric segmentation, and interseismic stress transfer (as described in Hierarchies 1–4), the computational model must be configured with high spatial and temporal resolution, thermomechanical realism, and appropriate numerical stability constraints. The simulations in this study achieve this by using a 2D visco-elasto-plastic framework implemented on a staggered Eulerian grid with over 35 million Lagrangian markers, a minimum spatial resolution of 200 m in critical fault zones, and adaptive time-stepping (down to 1 year) to resolve rupture processes. The thermal structure is imposed from inverted thermochronological datasets, while shear heating and slip-rate-dependent frictional weakening are explicitly modeled. Crucially, full-cycle simulations over ~10,000 years are run for multiple fault geometries and frictional parameter ranges to systematically explore the transition from ordinary (unimodal) to irregular (bimodal) seismic regimes. Although AI techniques are not explicitly applied in this paper, the computational demand and parameter sensitivity of this workflow present clear opportunities for AI integration — including the use of deep learning surrogates for rapid rupture prediction, Bayesian optimization for friction parameter tuning, or physics-informed neural networks (PINNs) for partially replacing the PDE solver with trainable components. Thus, the hypothesis is that this detailed, observation-constrained simulation setup is sufficient to replicate Himalayan seismic behavior — and potentially further enhanced by AI in future iterations."



DISCIPLINE = "geophysics"  

# INTRODUCTION_OF_HIERARCHIES: added to the hierarchy greedy search prompt
INTRODUCTION_OF_HIERARCHIES = "Here we propose a five-level hierarchy to organize the formulation of hypotheses in geophysical modeling workflows: (1) Geophysical Phenomenon or Problem Domain: Identifies the broad-scale tectonic or geodynamic phenomenon under investigation, such as subduction dynamics, fault slip behavior, or crustal deformation patterns. This sets the conceptual foundation for the modeling task and defines the physical behavior to be explained; (2) Governing Physical Principles: Establishes the core physical mechanisms—e.g., stress accumulation, elastic rebound, rate-dependent friction, or thermally activated creep—that are believed to govern the phenomenon. This is the theoretical backbone that explains how the system evolves under external forcing; (3) Numerical and Computational Framework: Translates the physical principles into a solvable form by selecting mathematical models (e.g., PDEs), discretization methods (e.g., finite element or finite difference), and numerical solvers. This level formulates how the physical laws are encoded computationally; (4) Parameterization and Physical Detail: Assigns specific values and configurations to model components—such as fault geometry, rheological properties, friction coefficients, and initial stress states—based on observations, laboratory data, or inversion results. This makes the model physically grounded and testable; (5) Simulation Setup, Execution Conditions, and AI Integration: Describes the practical aspects of running the model—domain size, boundary conditions, resolution, time-stepping schemes, and any AI-enhanced components like surrogate modeling or optimization. This level defines how the hypothesis is executed in silico."

# HIERARCHY_LIST, DESCRIPTION_HIERARCHY_LIST: added to the hierarchy greedy search prompt
HIERARCHY_LIST = ["Geophysical Phenomenon or Problem Domain", "Governing Physical Principles", "Numerical and Computational Framework", "Parameterization and Physical Detail", "Simulation Setup, Conditions, and AI Integration"]
DESCRIPTION_HIERARCHY_LIST = [
    f"Taking an organic {DISCIPLINE} example, the final fine-grained hypothesis of hierarchy (1) should look like this example: \n" + hyp_example_hierarchy_1 + f"\nIn this example, the {HIERARCHY_LIST[0]} are fully described.",
    f"Taking an organic {DISCIPLINE} example, the final fine-grained hypothesis of hierarchy (2) should look like this example: \n" + hyp_example_hierarchy_2 + f"\nIn this example, the {HIERARCHY_LIST[1]} are fully described, and are associated with {HIERARCHY_LIST[0]}.",
    f"Taking an organic {DISCIPLINE} example, the final fine-grained hypothesis of hierarchy (3) should look like this example: \n" + hyp_example_hierarchy_3 + f"\nIn this example, the {HIERARCHY_LIST[2]} are specified, and are well integrated with {HIERARCHY_LIST[0]} and {HIERARCHY_LIST[1]}.",
    f"Taking an organic {DISCIPLINE} example, the final fine-grained hypothesis of hierarchy (4) should look like this example: \n" + hyp_example_hierarchy_4 + f"\nIn this example, the {HIERARCHY_LIST[3]} are specified, and are well integrated with {HIERARCHY_LIST[0]}, {HIERARCHY_LIST[1]}, and {HIERARCHY_LIST[2]}.",
    f"Taking an organic {DISCIPLINE} example, the final fine-grained hypothesis of hierarchy (5) should look like this example: \n" + hyp_example_hierarchy_5 + f"\nIn this example, the {HIERARCHY_LIST[4]} are fully described, and are well integrated with {HIERARCHY_LIST[0]}, {HIERARCHY_LIST[1]}, {HIERARCHY_LIST[2]}, and {HIERARCHY_LIST[3]}."
]

# FEEDBACK_HIERARCHY_VALIDITY_CLARITY, FEEDBACK_NON_HIERARCHY_VALIDITY_CLARITY: added to the validity_clarity_feedback_to_hyp prompt
FEEDBACK_HIERARCHY_VALIDITY_CLARITY = [
    f"Here we are especially interested in feedback in terms of the geophysical phenomenon or problem domain: for example, what large-scale tectonic or dynamic process is being investigated (e.g., subduction, fault slip, lithospheric flexure), and how this process unfolds conceptually in space and time. This level is the theoretical “blueprint” that frames the entire modeling effort — it should clearly define what physical behavior or pattern we are trying to explain (such as episodic seismicity, crustal thickening, or aseismic creep), and why it is significant. The ultimate goal is to identify the most appropriate, clearly articulated, and physically grounded geophysical phenomena that best capture the research question, and to ensure they are well explained in terms of fundamental geophysical or physical principles.",
    f'''
    Here we are especially interested in feedback in terms of the governing physical principles: for example, what physical mechanisms (e.g., rate-dependent friction, elastic stress accumulation, ductile flow, thermal weakening) are responsible for driving the geophysical phenomenon under study. This level identifies the broader physical processes necessary for the behavior to emerge, without needing to specify how they are computed or parameterized. You may also consider whether other relevant physical mechanisms — even if not an obvious expansion of the current hypothesis — might be useful for capturing important dynamics, especially if they are commonly overlooked or simplified in existing models.

    The ultimate goal is to identify the optimal set of general physical principles, well grounded in geophysics or continuum mechanics, that work together to explain the observed phenomenon and that support an effective modeling strategy.

    You are also encouraged to provide feedback on the phenomenon-level hypothesis (Hierarchy 1) if it lacks clarity, validity, or relevance. If you recommend adding, removing, or revising a physical principle at this stage, you should also suggest how the conceptual geophysical blueprint (i.e., the higher-level phenomenon hypothesis) would be updated to better align with fundamental geophysical understanding.
    ''',
    f'''
    Here we are especially interested in feedback in terms of the numerical and computational framework used to represent the governing physical principles: for example, which specific numerical methods or modeling strategies have been selected (e.g., “finite element method for visco-elastic deformation,” “finite difference scheme for wave propagation,” “marker-in-cell for material advection”), and how well they serve the geophysical mechanism under investigation. This level makes the hypothesis testable by specifying how the physical laws are operationalized in a simulation.

    You may also consider whether there are alternative or complementary numerical strategies that might enhance model stability, resolution, or realism — even if they are not a direct continuation of the physical mechanisms or principles defined earlier. These might include different time-stepping schemes, boundary condition treatments, solver choices, or multi-scale modeling approaches that were overlooked but are relevant.

    The ultimate goal is to identify the optimal set of computational components that best implement the general physical principles (Hierarchy 2), which in turn best explain the geophysical phenomenon (Hierarchy 1).

    You are also encouraged to provide feedback on the governing physical principles or phenomenon-level hypothesis if they are unclear, incomplete, or not sufficiently supported. Particularly, if you suggest updating, replacing, or refining a numerical component, you should also revise the corresponding physical hypothesis and mechanism to ensure coherence and improved effectiveness — as judged by fundamental geophysical and computational modeling principles.
    ''',
    f'''
    Here we are especially interested in feedback in terms of the full details of the parameterization and physical components used in the geophysical model: for example, the exact numerical values and configurations of key inputs such as fault geometry (e.g., dip angles, segment depths), rock properties (e.g., density, viscosity, thermal conductivity), frictional coefficients (μs, μd), or thermally derived rheological transitions. These details ensure clarity, reproducibility, and physical realism, allowing researchers to simulate the system with precision and evaluate the validity of the hypothesis in a real-world context.

    You may also consider whether additional or alternative parameterizations — even those that might not seem like direct refinements of the existing setup — could strengthen the model, especially if they are overlooked but plausible given geological observations or lab data. These might include updated thermal profiles, geodetic constraints, or stress state estimates that provide critical nuance to the fault behavior being modeled.

    The ultimate goal is to define the most accurate and justifiable set of physical and geological details that best support the specific computational framework (Hierarchy 3), which in turn implements the governing physical principles (Hierarchy 2), and explains the overarching geophysical phenomenon (Hierarchy 1).

    You are also encouraged to provide feedback on any higher-level hypotheses — including the computational methods, physical principles, or even the conceptual framing of the phenomenon — if they lack clarity, integration, or physical validity. Particularly, if you suggest updating, removing, or introducing a specific parameter or geological detail, you should also update the relevant parts of the governing mechanism so that the new configuration better reflects fundamental geophysical understanding and improves the overall explanatory power of the model.
    ''',
    f'''
    Here we are especially interested in feedback in terms of the simulation setup and execution conditions: for example, the practical modeling configuration — including spatial and temporal resolution, boundary conditions, time-stepping schemes, domain size, simulation duration, computational resources used (e.g., GPU clusters), model runtime strategies, and any implemented or potential AI-based components (e.g., surrogate modeling, inversion, or optimization techniques). This hierarchy describes how the geophysical model is actually run and evaluated in a computational setting.

    You should consider whether key implementation details are missing, vague, or unjustified — for example, if a statement claims that "adaptive meshing ensures convergence near the fault tip," but the specific mesh resolution or convergence criterion is not reported, it should be noted. Similarly, if a modeling claim seems overly confident (e.g., “ensures accurate rupture timing”), a more cautious and qualified phrasing may be warranted unless robust validation is provided.

    The ultimate goal is to identify the most complete, accurate, and physically consistent set of simulation conditions that best implement the parameterized components (Hierarchy 4), computational methods (Hierarchy 3), physical mechanisms (Hierarchy 2), and geophysical problem definition (Hierarchy 1), thereby enabling reliable hypothesis testing and meaningful model output.

    You are also encouraged to provide feedback on any upstream hierarchies — including the physical mechanisms, numerical framework, or parameter details — if they appear misaligned, incomplete, or invalid in light of how the model is run. In particular, if you recommend updating or removing a setup feature (e.g., changing the fault mesh or adding an AI surrogate), you should also reflect on how this would impact the model’s effectiveness, clarity, or fidelity to fundamental geophysical principles.
    '''
]

FEEDBACK_NON_HIERARCHY_VALIDITY_CLARITY = [
    f'''
    In terms of the validity aspect, the ultimate goal is to identify the most coherent, physically grounded, and computationally implementable hypothesis to effectively address the geophysical research question.

    Here are some examples in terms of the clarity and specificity aspect:

    Example 1: The added information (or some existing information in the hypothesis) might state: “The model includes a non-planar fault geometry with a ramp-flat-ramp structure.” However, such a general statement is too vague for research or modeling purposes. Instead, you should explicitly define the geometry, such as: “The fault dip is 10° in the shallow segment (0–8 km), flattens at 2° between 8–20 km, and steepens again to 15° from 20–40 km depth.” Providing this level of structural detail, ideally constrained by geophysical observations or seismic inversion, allows the model to be reproducible and physically meaningful.

    Example 2: The added information might say: “Stress accumulation is modeled using elasto-visco-plastic rheology.” While conceptually accurate, this needs elaboration to be useful. What are the viscosity laws used? What yield criterion governs plastic failure? Instead of a general mention, the hypothesis should specify: “We use a temperature-dependent power-law viscosity with activation energy Q = 200 kJ/mol and a Drucker-Prager yield criterion with internal friction angle φ = 30°.” These numerical values and rheological laws give substance to the modeling framework and tie it to physical processes.

    Example 3: The added (or existing) hypothesis might say: “Adaptive time stepping ensures stability during rupture propagation.” In this case, the word “ensures” is too strong and unqualified. You should instead use more cautious, evidence-based phrasing, such as: “Adaptive time stepping, ranging from 0.1 to 5 years, was used to improve numerical stability during high-strain-rate rupture phases, although some instabilities were noted near the rupture front.” Also, explicitly defining the time step range or stability criterion helps clarify the model’s numerical robustness and limitations.

    In all cases, when suggesting the addition, removal, or refinement of a component — whether structural (e.g., fault geometry), physical (e.g., rheological behavior), or numerical (e.g., solver settings) — you should also update the corresponding part of the modeling hypothesis to maintain coherence across all layers of the model. The revised hypothesis should offer improved explanatory power, computational validity, and physical consistency, as judged from the fundamental principles of geophysics and numerical modeling.
    '''
]

# EXAMPLE_DESCRIPTION_FINAL_HYPOTHESIS: used in hierarchy_greedy_search_five_hierarchy
EXAMPLE_DESCRIPTION_FINAL_HYPOTHESIS = f"For example, a final hypothesis at hierarchy level (5) should include {HIERARCHY_LIST[0]}, {HIERARCHY_LIST[1]}, {HIERARCHY_LIST[2]}, and {HIERARCHY_LIST[3]}."

# EXAMPLE_UPDATE_NEW_HIERARCHY: used in hierarchy_greedy_search_five_hierarchy and recombination prompts
EXAMPLE_UPDATE_NEW_HIERARCHY = f"For example, if we are searching for {HIERARCHY_LIST[4]}, we should maintain the {HIERARCHY_LIST[0]}, {HIERARCHY_LIST[1]}, {HIERARCHY_LIST[2]}, and {HIERARCHY_LIST[3]} while we adding information on {HIERARCHY_LIST[4]}."