DISCIPLINE = "chemistry"


def instruction_prompts(module_name, assist_info=None):
    if module_name == "extract_general_concept":
        prompts = [f"You are a helpful assistant that extracts general concepts from a given hypothesis. THe general concept should be methodological component of the hypothesis, instead of the experimental component. For example, if a hypothesis is 'Investigate the development of structurally anisotropic hydrogels as versatile platforms for thermogalvanic energy harvesters. Explore how the modulation of ion-specific interactions, as understood through frameworks like the Hofmeister series, can influence both energy conversion efficiency and mechanical resilience. Consider strategies to induce controlled structural alignment within hydrophilic polymer matrices to enhance thermoelectric performance while addressing material flexibility and durability for sustainable energy harvesting from low-grade thermal gradients.', some general concepts are 'hydrogel', 'ion-specific interactions'. \
                   The research question is: \n", "\nThe hypothesis is: \n", "\nPlease extract two general concepts from the hypothesis. \
                   The general concepts should be the most important concepts that are related to the hypothesis. \
                   Please answer the question in the following response format. (response format: 'Reasoning Process: \nGeneral Concepts: concept1, concept2\n')"]
        return prompts
    elif module_name == "propose_new_concept_to_replace_general_concept":
        prompts = [f"You are a helpful assistant that given a research question, a hypothesis, and a selected concept in the hypothesis, you can propose a new parallel concept to replace a given general concept. The new concept should have no overlap with the selected concept, but has similar role in the hypothesis. The new concept should not be a duplicate of the selected concept or any other concept mentions in the hypothesis. The new concept should be new compared to any concept in the original hypothesis, but in the big picture has similar role as the selected concept. For example, if the hypothesis is developing a protein drug for a desease, and the selected concept is about 'protein drug', a new concept could be 'small molecule drug'. Here 'protein' and 'small molecule' are parallel concepts, and the hypothesis does not mention 'small molecule' before. It is not necessary for the new concept to be also relevant and useful to the research question, just make it parallel to the selected concept, and sometimes you are encouraged to propose a new concept that is not related to the research question, but is parallel to the selected concept (we want performance difference between the hypotheses with the original general concept and the hypotheses with the new general concept). The point is that the new concept should be parallel to the selected concept, and the new concept should be new compared to any concept in the original hypothesis, but in the big picture has similar role as the selected concept. \
                   The research question is: \n", "\nThe hypothesis is: \n", "\nThe selected general concept is: \n", "\nPlease propose a new concept to replace the selected general concept. \
                   Please answer the question in the following response format. (response format: 'Reasoning Process: \nNew Concept: new_concept\n')"]
        return prompts
    elif module_name == "synthesize_new_hyp_with_replaced_general_concept":
        prompts = [f"You are a helpful assistant that given a research question, a hypothesis, a selected concept in the hypothesis, and a new concept to replace the selected concept, you can synthesize a new hypothesis using the new concept as a substitute for the selected concept (used for similar goal & function) while not using the selected concept (since it is replaced with the new concept). The concepts other than the selected concept and the new concept to replace the selected concept should be kept the same, no more, no less. The new hypothesis should be very close to the original hypothesis while only substituting the selected concept with the new concept in a way that is parallel to the original hypothesis. For example, if the hypothesis is developing a protein drug for a desease, and the selected concept is about 'protein drug', a new concept could be 'small molecule drug', a new hypothesis could be 'developing a small molecule drug for a desease'. \
                   The research question is: \n", "\nThe hypothesis is: \n", "\nThe selected general concept is: \n", "\nThe new concept to replace the selected general concept is: \n", "\nPlease synthesize a new hypothesis with the replaced general concept. \
                   Please answer the question in the following response format. (response format: 'Reasoning Process: \nNew Hypothesis: \n')"]
        return prompts
    elif module_name == "naming_specific_concept":
        prompts = [f"You are a helpful assistant that given a research question, a hypothesis, and a general concept, you can propose a list of (4~6) specific concepts that belong to the general concept and are the most relevant to the research question from that general concept (just try its best, but it is also possible that the general concept is not related to the research question, and therefore the specific concepts are not related to the research question, it is okay). For example, if the general concept is 'protein drug', the specific concepts could be a list of specific protein drugs such as Monoclonal Antibodies, Enzyme Replacement Therapies, etc. \
                   The research question is: \n", "\nThe hypothesis is: \n", "\nThe general concept is: \n", "\nPlease propose a list of specific concepts that belong to the general concept and are the most relevant to the research question in terms of inside this research hypothesis from that general concept. \
                   Please answer the question in the following response format. (response format: 'Reasoning Process: \nSpecific Concepts: specific_concept1, specific_concept2, specific_concept3\n')"]
        return prompts
    elif module_name == "synthesize_new_hyp_with_specific_concept":
        prompts = [f"You are a helpful assistant that given a research question, a hypothesis, a general concept, and a specific concept, you can synthesize a new hypothesis using the specific concept as a substitute for the general concept (used for similar goal & function) while not using the general concept (since it is replaced with the specific concept). The concepts other than the general concept and the specific concept to replace the general concept should be kept the same, no more, no less, no more general, no more specific. The new hypothesis should be very close to the original hypothesis while only substituting the general concept with the specific concept in a way that is parallel to the original hypothesis. For example, if the hypothesis is developing a protein drug for a desease, and the general concept is about 'protein drug', a specific concept could be 'Monoclonal Antibodies', a new hypothesis could be 'Developing Monoclonal Antibodies for a desease'. \
                   The research question is: \n", "\nThe hypothesis is: \n", "\nThe general concept is: \n", "\nThe specific concept to replace the general concept is: \n", "\nPlease synthesize a new hypothesis with the specific concept. \
                   Please answer the question in the following response format. (response format: 'Reasoning Process: \nNew Hypothesis: \n')"]
        return prompts
    elif module_name == "scoring_each_hyp_with_specific_concept":
        prompts = [f"""
                    You are a rigorous and detail-oriented reviewer in {DISCIPLINE}. Known for your critical approach, you generally assign low scores unless the hypothesis is truly exceptional.

                    Given a not-yet-peer-reviewed research hypothesis in {DISCIPLINE}, evaluate it based on the aspect of **Validness**.

                    The hypothesis should be scored on a scale from 0 to 100, considering the **feasibility**, **logical coherence**, and **theoretical support** of the hypothesis. Pay close attention to the following factors:

                    1. **Logical Progression**: Are the assumptions and conclusions well-justified and consistent? Does each assumption logically follow from the previous one, or are there weak or speculative steps?
                    2. **Empirical/Theoretical Support**: Does the hypothesis rely on well-established theory and data, or does it make weak or untested assumptions? How strongly is the hypothesis grounded in current research in {DISCIPLINE}?
                    3. **Practical Feasibility**: How likely is it that this hypothesis could be experimentally tested or implemented, given current technological or methodological constraints? Are the assumptions feasible given the limitations of current knowledge or technology?
                    4. **Assumption Strength**: Are any of the assumptions speculative or lacking solid backing? How much do these assumptions weaken the overall hypothesis?

                    High scores (75-100) should be reserved for hypotheses with strong theoretical grounding, logical coherence, and high feasibility. Lower scores (0-50) should reflect uncertainty, weak assumptions, or inconsistencies with well-established scientific principles.

                    **Scoring Guidelines for Validness (Objective Soundness)**  
                    Score the hypothesis between 0 and 100, with any value within that range being valid. Below are sample descriptions of each possible score to guide your evaluation. The full spectrum of 0 to 100 is encouraged.

                    - **100 — Ironclad Validity**: Exceptionally coherent, fully grounded in theory, and free from weak assumptions. (e.g., the hypothesis is a natural and logical extension of current research, strongly supported by existing theory and data, with no significant uncertainties.)
                    - **95 — Robust Validity**: Nearly flawless, with very minor uncertainties or assumptions that do not undermine the overall hypothesis. (e.g., the hypothesis is highly probable and consistent with theory, though it may involve some untested assumptions that are plausible.)
                    - **90 — High Confidence Validity**: Strong validity with a few weak assumptions or areas lacking empirical data, but overall highly reasonable. (e.g., the hypothesis is highly likely to be correct, though further evidence or validation may be needed in specific areas.)
                    - **85 — Solid Validity**: Well-supported by theory and data, with only a few minor speculative elements that do not significantly weaken it. (e.g., the hypothesis is grounded in existing research but relies on some assumptions that have not been fully verified.)
                    - **80 — Strong Validity**: Mostly reasonable, though some assumptions may be tenuous or speculative. (e.g., the hypothesis fits with known principles, but some of the underlying assumptions are weaker or not fully supported.)
                    - **75 — Moderate Validity**: A plausible hypothesis, but certain key assumptions lack strong theoretical or empirical support. (e.g., the hypothesis could work, but it relies on weak or underdeveloped assumptions that make it somewhat uncertain.)
                    - **70 — Fair Validity**: Reasonable in parts, but contains multiple speculative or untested assumptions. (e.g., the hypothesis has potential, but many aspects are based on assumptions that are not fully grounded in theory or data.)
                    - **60 — Questionable Validity**: Plausible but weak. The hypothesis faces serious limitations due to speculative reasoning or gaps in theory. (e.g., the hypothesis could work in principle, but its assumptions are largely untested or lack clear theoretical backing.)
                    - **50 — Marginal Validity**: Weak or speculative reasoning. The hypothesis is only moderately supported by existing research or theory. (e.g., the hypothesis is unlikely to be correct or testable, relying on numerous weak or unverified assumptions.)
                    - **40 — Low Validity**: Inconsistent or unsupported by established principles. The hypothesis is unlikely to work based on current knowledge, though there may be some merit in further exploration. (e.g., the hypothesis contradicts well-established principles and has limited theoretical or empirical backing.)
                    - **30 — Fragile Validity**: Highly unlikely and inconsistent with most known theories. The assumptions are implausible or unreasonably speculative. (e.g., the hypothesis has very weak theoretical grounding, with assumptions that are unrealistic or unsupported.)
                    - **20 — Implausible Validity**: Major contradictions with well-established scientific principles. The hypothesis proposes mechanisms that are highly improbable or infeasible. (e.g., the hypothesis contradicts key scientific principles and cannot be reconciled with current understanding.)
                    - **10 — Rejected Validity**: Fundamentally flawed and not testable. The hypothesis presents ideas that are in direct contradiction with multiple established principles. (e.g., the hypothesis presents concepts or assumptions that are fundamentally at odds with scientific knowledge.)
                    - **0 — Non-Scientific**: Completely unsupportable. The hypothesis is beyond current scientific reasoning and is not testable or reconcilable with known science. (e.g., the hypothesis proposes mechanisms or ideas that are not only unsupported but impossible to test or validate within the scientific framework.)

                    **The research question is:**
                    """, "\nThe hypothesis is: \n", "\nPlease score the hypothesis from the aspect of Validness. \
                    Please answer the question in the following response format. (response format: 'Reasoning Process: \nScore: \n')"]
        return prompts
    else:
        raise NotImplementedError